"""empty message

Revision ID: 1740123160fb
Revises: 
Create Date: 2017-10-30 22:38:24.772360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1740123160fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sort', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('sort', sa.String(), nullable=True),
    sa.Column('author_sort', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('pubdate', sa.String(), nullable=True),
    sa.Column('series_index', sa.String(), nullable=True),
    sa.Column('last_modified', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('has_cover', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('datatype', sa.String(), nullable=True),
    sa.Column('mark_for_delete', sa.Boolean(), nullable=True),
    sa.Column('editable', sa.Boolean(), nullable=True),
    sa.Column('display', sa.String(), nullable=True),
    sa.Column('is_multiple', sa.Boolean(), nullable=True),
    sa.Column('normalized', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publishers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sort', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sort', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books_authors_link',
    sa.Column('book', sa.Integer(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['book'], ['books.id'], ),
    sa.PrimaryKeyConstraint('book', 'author')
    )
    op.create_table('books_languages_link',
    sa.Column('book', sa.Integer(), nullable=False),
    sa.Column('lang_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book'], ['books.id'], ),
    sa.ForeignKeyConstraint(['lang_code'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('book', 'lang_code')
    )
    op.create_table('books_publishers_link',
    sa.Column('book', sa.Integer(), nullable=False),
    sa.Column('publisher', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book'], ['books.id'], ),
    sa.ForeignKeyConstraint(['publisher'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('book', 'publisher')
    )
    op.create_table('books_ratings_link',
    sa.Column('book', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book'], ['books.id'], ),
    sa.ForeignKeyConstraint(['rating'], ['ratings.id'], ),
    sa.PrimaryKeyConstraint('book', 'rating')
    )
    op.create_table('books_series_link',
    sa.Column('book', sa.Integer(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book'], ['books.id'], ),
    sa.ForeignKeyConstraint(['series'], ['series.id'], ),
    sa.PrimaryKeyConstraint('book', 'series')
    )
    op.create_table('books_tags_link',
    sa.Column('book', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book'], ['books.id'], ),
    sa.ForeignKeyConstraint(['tag'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('book', 'tag')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('book', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('uncompressed_size', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['book'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('val', sa.String(), nullable=True),
    sa.Column('book', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identifiers')
    op.drop_table('data')
    op.drop_table('comments')
    op.drop_table('books_tags_link')
    op.drop_table('books_series_link')
    op.drop_table('books_ratings_link')
    op.drop_table('books_publishers_link')
    op.drop_table('books_languages_link')
    op.drop_table('books_authors_link')
    op.drop_table('tags')
    op.drop_table('series')
    op.drop_table('ratings')
    op.drop_table('publishers')
    op.drop_table('languages')
    op.drop_table('custom_columns')
    op.drop_table('books')
    op.drop_table('authors')
    # ### end Alembic commands ###
